APP_NAME := radioplus
SRCS     := radioplus.c ui.c \
            core/fmcmd.c core/fmreg.c core/rds.c core/region.c \
            core/wav.c core/store.c \
            platform/model_device.c
LV_SURFACE := 1
include ../../sdk/hb_app.mk
