#!/bin/bash
# Generate the measured program tables into core/measured.c and core/measured.h.
#
# Run after re-running the analysis:
#     bash tools/gen-measured.sh
set -u
PY="/c/Program Files/Python313/python.exe"
cd "$(dirname "$0")/.." || exit 1

OUT=core/measured.c
HDR=core/measured.h

names=("Practice 1" "Practice 2" "Practice 3" "Practice 4" "Practice 5" "Practice 6")

{
cat <<'HEADER'
/*
 * measured.c — programs measured from recordings. Generated; do not hand-edit.
 *
 * Produced by tools/analyse-layers.py and tools/port-measured.py. What was
 * taken from the recordings is a measurement: per carrier band, the carrier
 * frequency, the beat between the two channels, and how present that band is,
 * sampled every four seconds. Numbers and timings. Nothing of the recordings
 * themselves is here, and Entrain synthesises its own tones from these.
 *
 * The names are deliberately neutral and are not the originals. That follows
 * the same rule the imported suites follow, and the reason is in README.md
 * under Trademark: this app is not affiliated with, endorsed by or derived
 * from the organisation whose practice material was measured, and using its
 * exercise names would suggest otherwise.
 *
 * Every band that actually sounds is carried as its own layer, including the
 * stretches where its gain is zero - a layer that goes quiet for ten minutes
 * and returns is what the recording does, and flattening that would be
 * discarding a measurement.
 *
 * Regenerate with tools/gen-measured.sh.
 */

#include "measured.h"

HEADER

for i in 1 2 3 4 5 6; do
    "$PY" tools/port-measured.py "tools/analysis/layers-$i.json" \
          --name "${names[$((i-1))]}" --bin 30
    echo
done
} > "$OUT"

# The tables are listed from program.c, so they need external linkage and a
# header. Both are emitted here rather than maintained by hand, so the segment
# counts in the header cannot drift from the tables in the source.
sed -i 's/^static const en_prog_seg_t s_/const en_prog_seg_t en_meas_/' "$OUT"

{
    echo "/*"
    echo " * measured.h — generated by tools/gen-measured.sh; do not hand-edit."
    echo " *"
    echo " * The tables in measured.c and their lengths. program.c lists these"
    echo " * among the suites; nothing else should need them."
    echo " */"
    echo
    echo "#ifndef ENTRAIN_MEASURED_H"
    echo "#define ENTRAIN_MEASURED_H"
    echo
    echo '#include "program.h"'
    echo
    for i in 1 2 3 4 5 6; do
        n=$(sed -n "/^const en_prog_seg_t en_meas_practice_$i\[\]/,/^};/p" "$OUT" \
            | grep -c '^    { \.beat_start')
        echo "#define EN_MEAS_PRACTICE_${i}_SEGS $n"
        echo "extern const en_prog_seg_t en_meas_practice_$i[EN_MEAS_PRACTICE_${i}_SEGS];"
    done
    echo
    echo "#endif /* ENTRAIN_MEASURED_H */"
} > "$HDR"

echo "wrote $OUT and $HDR"
echo "  $(grep -c '^    { \.beat_start' "$OUT") segments total"
grep '^#define EN_MEAS' "$HDR"
