APP_NAME   := entrain
SRCS       := entrain.c ui.c engine.c \
              core/osc.c core/noise.c core/render.c core/program.c \
              core/wavout.c \
              platform/audio_device.c platform/sys_device.c
LV_SURFACE := 1
include ../../sdk/hb_app.mk
