/*
 * measured.h — generated by tools/gen-measured.sh; do not hand-edit.
 *
 * The tables in measured.c and their lengths. program.c lists these
 * among the suites; nothing else should need them.
 */

#ifndef ENTRAIN_MEASURED_H
#define ENTRAIN_MEASURED_H

#include "program.h"

#define EN_MEAS_PRACTICE_1_SEGS 31
extern const en_prog_seg_t en_meas_practice_1[EN_MEAS_PRACTICE_1_SEGS];
#define EN_MEAS_PRACTICE_2_SEGS 51
extern const en_prog_seg_t en_meas_practice_2[EN_MEAS_PRACTICE_2_SEGS];
#define EN_MEAS_PRACTICE_3_SEGS 22
extern const en_prog_seg_t en_meas_practice_3[EN_MEAS_PRACTICE_3_SEGS];
#define EN_MEAS_PRACTICE_4_SEGS 38
extern const en_prog_seg_t en_meas_practice_4[EN_MEAS_PRACTICE_4_SEGS];
#define EN_MEAS_PRACTICE_5_SEGS 19
extern const en_prog_seg_t en_meas_practice_5[EN_MEAS_PRACTICE_5_SEGS];
#define EN_MEAS_PRACTICE_6_SEGS 12
extern const en_prog_seg_t en_meas_practice_6[EN_MEAS_PRACTICE_6_SEGS];

#endif /* ENTRAIN_MEASURED_H */
